microrant/config/routes.rb
Microrant::Application.routes.draw do
  resources :rants

  resources :users

  root :to => "rants#index"

end

microrant/app/models/rant.rb
class Rant < ActiveRecord::Base

  belongs_to :user

  validates :user, :presence => true
  validates :message, :presence => true, :length => { :maximum => 10 }
  #validates :message, :length => { :within => 1..10 }

end

microrant/app/models/user.rb
class User < ActiveRecord::Base

  has_many :rants
  
  validates :name, :presence => true

end

microrant/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

microrant/app/controllers/rants_controller.rb
class RantsController < ApplicationController
  # GET /rants
  # GET /rants.xml
  def index
    @rants = Rant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rants }
    end
  end

  # GET /rants/1
  # GET /rants/1.xml
  def show
    @rant = Rant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rant }
    end
  end

  # GET /rants/new
  # GET /rants/new.xml
  def new
    @rant = Rant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rant }
    end
  end

  # GET /rants/1/edit
  def edit
    @rant = Rant.find(params[:id])
  end

  # POST /rants
  # POST /rants.xml
  def create
    @rant = Rant.new(params[:rant])

    respond_to do |format|
      if @rant.save
        format.html { redirect_to(@rant, :notice => 'Rant was successfully created.') }
        format.xml  { render :xml => @rant, :status => :created, :location => @rant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rants/1
  # PUT /rants/1.xml
  def update
    @rant = Rant.find(params[:id])

    respond_to do |format|
      if @rant.update_attributes(params[:rant])
        format.html { redirect_to(@rant, :notice => 'Rant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rants/1
  # DELETE /rants/1.xml
  def destroy
    @rant = Rant.find(params[:id])
    @rant.destroy

    respond_to do |format|
      format.html { redirect_to(rants_url) }
      format.xml  { head :ok }
    end
  end
end

microrant/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

microrant/app/helpers/application_helper.rb
module ApplicationHelper
end

microrant/app/helpers/rants_helper.rb
module RantsHelper
end

microrant/app/helpers/users_helper.rb
module UsersHelper
end

microrant/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microrant</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

microrant/app/views/rants/_form.html.erb
<%= form_for(@rant) do |f| %>
  <% if @rant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rant.errors.count, "error") %> prohibited this rant from being saved:</h2>

      <ul>
      <% @rant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

microrant/app/views/rants/edit.html.erb
<h1>Editing rant</h1>

<%= render 'form' %>

<%= link_to 'Show', @rant %> |
<%= link_to 'Back', rants_path %>

microrant/app/views/rants/index.html.erb
<h1>Listing rants</h1>

<table>
  <tr>
    <th>User</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rants.each do |rant| %>
  <tr>
    <td><%= rant.user_id %></td>
    <td><%= rant.message %></td>
    <td><%= link_to 'Show', rant %></td>
    <td><%= link_to 'Edit', edit_rant_path(rant) %></td>
    <td><%= link_to 'Destroy', rant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rant', new_rant_path %>

microrant/app/views/rants/new.html.erb
<h1>New rant</h1>

<%= render 'form' %>

<%= link_to 'Back', rants_path %>

microrant/app/views/rants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rant.user_id %>
</p>

<p>
  <b>Message:</b>
  <%= @rant.message %>
</p>


<%= link_to 'Edit', edit_rant_path(@rant) %> |
<%= link_to 'Back', rants_path %>

microrant/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

microrant/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

microrant/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

microrant/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

microrant/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>